version: '3.9'

services:
  bot:
    build: .
    container_name: telegram_realty_bot
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["python", "bot.py"]

  webhook:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "443:443"
    depends_on:
      - bot